<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHxwqa9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHxwqa9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHxwqa9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHxwqa9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXHxwqa9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XHxwqa9',
    'container.build_id' => '41cd0110',
    'container.build_time' => 1551256414,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHxwqa9');
