<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTWsqvvn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTWsqvvn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTWsqvvn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTWsqvvn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTWsqvvn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TWsqvvn',
    'container.build_id' => '337d7506',
    'container.build_time' => 1551283916,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTWsqvvn');
