<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGfEMJR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGfEMJR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGfEMJR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGfEMJR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXGfEMJR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XGfEMJR',
    'container.build_id' => 'cc315301',
    'container.build_time' => 1551259651,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGfEMJR');
